### ISSUE TITLE
Most recent changes to enable enter mode settings

### ISSUE THREAD

**Issue by Marnix-IxD** [mendix/CKEditorForMendix#11]
The changes only affect "entermode" can you please implement the auto paragraph and shiftenter mode settings too?

**Comment by JelteMX** [comment]
Can you please explain what you mean exactly? You're missing some plugins?

**Comment by Marnix-IxD** [comment]
The below settings would be desired:

config.enterMode = CKEDITOR.ENTER_BR // pressing the ENTER KEY input <br/>

The new changse only afflict the above config, but i would like the below settings to be set too:

config.shiftEnterMode = CKEDITOR.ENTER_P; //pressing the SHIFT + ENTER KEYS input <p>
config.autoParagraph = false; // stops automatic insertion of <p> on focus

**Comment by JelteMX** [comment]
Fixed in the [latest release](https://github.com/mendix/CKEditorForMendix/releases/tag/v1.7.0)
