### ISSUE TITLE
More prominent place for the version number of the CKEditor

### ISSUE THREAD

**Issue by RCatersels** [mendix/CKEditorForMendix#14]
You have to dig deep to find which version number of the CKeditor is used. Could this info get a prominent place in the documentation? And I am wondering if the option to strip the Word copy paste function automaticly is turned on. From the documentation I read that this is turned on by default from a certain version. Before that you had to use the special button to copy paste from Word. But since users did not use this they turned the option to strip the copy paste from Word by default. 

And is my understanding correct that the with the URL in the documentation to create a new specific version of the CKeditor that you get a new version that you just have to drop into the widget to get the widget with the latest version?

Regards,

Ronald

**Comment by JelteMX** [comment]
Hi Ronald,

> You have to dig deep to find which version number of the CKeditor is used. Could this info get a prominent place in the documentation?

We recently updated the CKEditor to the latest version. I think it is a good idea to include the version number in the documentation.

> I am wondering if the option to strip the Word copy paste function automaticly is turned on.

We will check if that is the case. I think it should be automatically on, right?

> And is my understanding correct that the **with the URL in the documentation to create a new specific version of the CKeditor** that you get a new version that you just have to drop into the widget to get the widget with the latest version?

Could you elaborate on that? I don't know which URL you are referring to. We use this repository as the base for the widget on the App Store. So technically yes, if we create a new version of the widget it is placed here first ([Releases](https://github.com/mendix/CKEditorForMendix/releases)), then we push a new update to the App Store

**Comment by RCatersels** [comment]
In the build-config.js there is a URL: http://ckeditor.com/builder/download/e28e1c17acaeb42364c092d2fe181fc5
It will then use the latest CKeditor with the same options as you used last time to create the version.
So I wondered if I replace the files in the widget with the files I get from that URL I have the widget with the latest CKEditor in them. Or do you need to configure something more to rebuild the widget? 

And yes please the auto strip from Word should be turned on. 
Thank you very much.

Regards,

Ronald

**Comment by JelteMX** [comment]
Ah, like that! Yes, that is true. We include the build-config.js to download all the plugins on the CKEditor website. There is just one exception (this is now done manually), we have created one plugin ourselves [mendixlink](https://github.com/mendix/CKEditorForMendix/tree/master/src/CKEditorForMendix/widget/lib/plugins/mendixlink) which is the Microflow button.

**Comment by RCatersels** [comment]
Ok, thanks. Then I know what I have to do if I want a new version in a hurry :).

Thank you. And yes the table plugin would be nice to. I needed that last week. I got it to work but this was not something I would as of our clients (most of the time they create their own templates).
