### ISSUE TITLE
Table controls for adding or removing columns and rows

### ISSUE THREAD

**Issue by David-Sanders** [mendix/CKEditorForMendix#19]
It looks like the plugin.js file is missing from the CKEditorForMendix\widget\lib\plugins\tabletools directory. Adding this file (downloaded from http://ckeditor.com/addon/tabletools) adds a right-click context menu to the tables which allows easier control of table functionality. 

Without this there are strange mis-positioned controls for some of this functionality.  This relates to https://mxforum.mendix.com/questions/9058/CKEditor-widget-controls

**Comment by JelteMX** [comment]
Fixed in [1.7.1](https://github.com/mendix/CKEditorForMendix/releases/tag/v1.7.1)

**Comment by David-Sanders** [comment]
Thank you - it seems to be working OK now... David
