### ISSUE TITLE
Can you add the possibilty to embed images into the text from a user lib based on system.image

### ISSUE THREAD

**Issue by ykleefkens** [mendix/CKEditorForMendix#22]

**Comment by JelteMX** [comment]
Duplicate feature request: #24 

We're working on this feature on a seperate branch: https://github.com/mendix/CKEditorForMendix/tree/feature/imageupload, and currently testing. Hopefully we'll update this in the AppStore next week

**Comment by JelteMX** [comment]
Added in [v1.9.0](https://github.com/mendix/CKEditorForMendix/releases/tag/v1.9.0)
