### ISSUE TITLE
No constructor found for widget CKEditorForMendix.widget.CKEditorViewerForMendix

### ISSUE THREAD

**Issue by RCatersels** [mendix/CKEditorForMendix#32]
Jelte,
I have also a support ticket for this (464960) but this problem is getting very frustrating. Only when working on the local machine everywhere where the CKEditor is used I get the No constructor found error (on all the machines in our office in Mx 516.1 we had this occasionally but since 5.21 everywhere). When I deploy the model to the cloud all works as expected. But this make local debuging and testing very hard. Any idear what might cause this?

Regards,

Ronald

**Comment by JelteMX** [comment]
We're working on analysing this problem.

**Comment by JelteMX** [comment]
We updated to [v2.0.4](https://github.com/mendix/CKEditorForMendix/releases/tag/v2.0.4) which will fix this issue. Updating it in the AppStore tomorrow. You can test this by downloading the enclosed .mpk file.

We also added this to your support ticket.

**Comment by RCatersels** [comment]
Thank you Jelte. Your the greatest. Very happy.

 

Regards,

 

Ronald

 

 

Van: Jelte Lagendijk [mailto:notifications@github.com] 
Verzonden: donderdag 10 maart 2016 16:51
Aan: mendix/CKEditorForMendix <CKEditorForMendix@noreply.github.com>
CC: Ronald Catersels <ronald.catersels@daywize.nl>
Onderwerp: Re: [CKEditorForMendix] No constructor found for widget CKEditorForMendix.widget.CKEditorViewerForMendix (#32)

 

We updated to v2.0.4 <https://github.com/mendix/CKEditorForMendix/releases/tag/v2.0.4>  which will fix this issue. Updating it in the AppStore tomorrow. You can test this by downloading the enclosed .mpk file.

We also added this to your support ticket.
