### ISSUE TITLE
CR/LF automatically added at end of text

### ISSUE THREAD

**Issue by Martin-UMCU** [mendix/CKEditorForMendix#35]
When entering plain text using the CKEditor, we notice that an CR/LF is automatically added at the end of the text. This should not be the case (only when the user explicitly presses ENTER).

**Comment by JelteMX** [comment]
![screen shot 2016-05-11 at 11 56 01](https://cloud.githubusercontent.com/assets/14937393/15178724/993b2698-1777-11e6-80f8-6114c1dfc90b.png)

If you set ``Autoparagraph`` to ``No``, it will not add a CR/LF

**Comment by Martin-UMCU** [comment]
I do not agree, since this  option is clearly marked as **deprecated** and changing the default value might **introduce unpredictable usability issues and is highly unrecommended.**
Is there maybe another future proof and reliable option for the CKEditor to prevent an CR/LF being automatically added at the end of the text.

**Comment by JelteMX** [comment]
Unfortunately not, I've checked the CKEditor repository and documentation. So this is a limitation that is not related to this widget, but to the [CKEditor ](https://github.com/ckeditor/ckeditor-dev)library
