### ISSUE TITLE
Page will not open when a Viewer contains an attribute which is not readable nor writeable 

### ISSUE THREAD

**Issue by davelina** [mendix/CKEditorForMendix#39]
Thanks for the widget, it is beautiful!

When the viewer contains an attribute which is not readable nor writeable (so you don't have any access) it will block loading the entire page you try to open. 

In Chrome Developer Tools it will give you the following error:
`An error occurred while handling queued requests: mxui_widget_DataView_95.applyContext: Error: CKEditorForMendix_widget_CKEditorViewerForMendix_6.applyContext: Error: CKEditorForMendix_widget_CKEditorViewerForMendix_6.applyContext: TypeError: Cannot read property 'split' of null`

Our expectation:
We would expect that you can't view the attribute value, but this would not block loading a page. You simply won't see any value (the normal behavior of an attribute when using access rules). 

If you need some more info, please contact me. 

Regards, 
Dave

**Comment by JelteMX** [comment]
Can you test [this version](https://github.com/mendix/CKEditorForMendix/raw/master/test/widgets/CKEditorForMendix.mpk) and let me know if this fixes your problem?

**Comment by davelina** [comment]
Hi Jelte, 

It still not working unfortunately. 
We created a testproject (modellere 6.5.1). 

Explanation: 

1. Log in as MxAdmin - 1
2. Create a new record
3. Go to demo user: demo_user
4. Click the buttons: 'Lees en schrijf', 'Lees', 'Geen rechten'. 
5. The last one will not give any result. 

Demo_user has no rights on the element which is shown in the form 'Geen rechten'. 
Because the demo_user has no rights at all on this attribute, the page will not load and when you open the developer tools in Chrome you will see the error. 

Hopefully this can help you fixing the issue. 

Thanks! 

Ps. unzip first, then you got the .mpk 

[Test app CKEditor.zip](https://github.com/mendix/CKEditorForMendix/files/293257/Test.app.CKEditor.zip)

**Comment by JelteMX** [comment]
Thanks. I'll have look at it this week and see if we can further fix it.

**Comment by JelteMX** [comment]
Due to [Mendix World](https://www.mendix.com/mendix-world/) I am moving this issue back to later this week

**Comment by RCatersels** [comment]
Jelte, did you already talk with R&D about this issue?

**Comment by JelteMX** [comment]
Nope. Due to sick-leave (and my colleague being on vacation) I haven't had the time to resolve this issue. It's on my todo for next week

**Comment by rickyv3** [comment]
We have run into a similar issue in 6.9.1, where we receive the following error:

mxui.js?636128950893645105:29 mendix.sys.Data.get: error in handler for 27866022694364145: CKEditorForMendix_widget_CKEditorForMendix_0.applyContext: Error: CKEditorForMendix_widget_CKEditorForMendix_0.applyContext: TypeError: Cannot read property 'setReadOnly' of undefined
