### ISSUE TITLE
Hide the statusbar of the widget by default

### ISSUE THREAD

**Issue by dan-covaliu** [mendix/CKEditorForMendix#41]
As an enhancement, could you add the option to hide (default-yes) the trail of html attributes that are displayed in the status bar at the bottom of the widget. This trail, by default " div p", is confusing to our end-users, it doesn't tell them anything useful. Alternatively, you could make it so that the entire status bar is hidden by default - this will save further space in the page. Thank you.

**Comment by JelteMX** [comment]
This will be available in the next [release](https://github.com/mendix/CKEditorForMendix/releases) 2.2.0 (not available yet). Hiding statusbar will not be default, but optionally.
