### ISSUE TITLE
IFrame embedding

### ISSUE THREAD

**Issue by rvhofwegen** [mendix/CKEditorForMendix#42]
Please add Iframe option to CK editor.

**Comment by RoelandSalij** [comment]
Do you mean this: http://ckeditor.com/addon/iframe ?

**Comment by rvhofwegen** [comment]
Yes indeed. To embed a model share.
Op 16 jun. 2016 13:59 schreef "Roeland Salij" <notifications@github.com>:

**Comment by JelteMX** [comment]
This is already included in the insert bar in CKEditor
