### ISSUE TITLE
Remove tooltip 

### ISSUE THREAD

**Issue by dan-covaliu** [mendix/CKEditorForMendix#46]
As an enhancement, remove the tooltip on the control. It is jibberish for our end users and there is no way to disable that. Thanks!

**Comment by JelteMX** [comment]
What do you mean jibberish? Tooltips are used to let a person know what a button means. This is quite normal

**Comment by dan-covaliu** [comment]
Sorry for misleading you; it's about tooltips on the edit area, not the buttons:
![image](https://cloud.githubusercontent.com/assets/16047546/16267358/5dc28d1c-3857-11e6-915e-e84967a8e347.png)

**Comment by edwinmp** [comment]
Issue fixed in pull request https://github.com/mendix/CKEditorForMendix/pull/49
Includes an option to either show or hide the tooltip, and set custom text for it.

**Comment by JelteMX** [comment]
Fixed in [2.4.0](https://github.com/mendix/CKEditorForMendix/releases/tag/v2.4.0)
