### ISSUE TITLE
Indent/Outdent breaks page in IE

### ISSUE THREAD

**Issue by jeroen-huizer-conclusion** [mendix/CKEditorForMendix#52]
Using the indent or outdent buttons will 'break' the widget in IE 11.
I am using the BootstrapRTE on a simple page (no other widgets / inputs) in an otherwise empty project.

A little debugging leads to the document.execCommand call causing the problem.
When triggering that function directly through the console, the problem occurs as well.

Any idea what could cause this?

Regards,
Jeroen Huizer

![image](https://cloud.githubusercontent.com/assets/21953339/22067169/5fa37edc-dd90-11e6-940a-6fd2190f4b2a.png)

![image](https://cloud.githubusercontent.com/assets/21953339/22067204/8b8a08f4-dd90-11e6-9909-c6af1526c294.png)

**Comment by JelteMX** [comment]
This is the CKEditor, not the [BootstrapRTE](https://github.com/mendix/Bootstrap-RTE) editor

**Comment by jeroen-huizer-conclusion** [comment]
Whoops, my bad. Will open issue there.
