### ISSUE TITLE
CKEditor throwing errors in Mendix v7 app

### ISSUE THREAD

**Issue by Starsnip** [mendix/CKEditorForMendix#54]
Please see question here.

https://forum.mendixcloud.com/link/questions/86334

I don't have enough experience to be able to confirm it's a CKEditor issue, but thought I'd raise it here, as I've updated CKEditor and it's still giving the same issue.

Tarique

**Comment by JelteMX** [comment]
I checked the issue on the forum, you need to update to the latest version. If you did, this is not an issue with the CKEditor (I tested and fixed issues for Mendix 7, should be working). I think this has to do with some rogue other widget.

Without a specific error to point at, I can't do anything. It's best to open a ticket with Support (so you can provide a test-project that will reproduce the problem). CKEditor is supported.

**Comment by Starsnip** [comment]
Thanks for the response.  I did update to the latest version, and the page
in question is fairly sparse in terms of other widgets.  We're leaving the
migration at present, as it seems a little early but will revisit in a few
weeks.  Thanks again.
