### ISSUE TITLE
CKE editor default paragraph added to every element in the html,

### ISSUE THREAD

**Issue by Marnix-IxD** [mendix/CKEditorForMendix#8]
Currently the mendix CKE editor adds paragraphs to each HTML element by default

I personally dislike this behavior because it affects styling in bad way, sure all regular text elements should have a paragraph added to them, but images should not, they would be better off having a <div> or nothing

I would really like it if in a future version this could be improved.

**Comment by JelteMX** [comment]
We have added 'enterMode' to the widget, see [release v1.6.2](https://github.com/mendix/CKEditorForMendix/releases/tag/v1.6.2), where you can choose how the editor must behave on Enter. Have a look at: http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-enterMode
